### ISSUE TITLE
We should easily be able to override the mailer

### ISSUE THREAD

**Issue by frobichaud** [mcordell/grape_token_auth#15]
There should be a config that allows devs to override the mailer, perhaps something similar to:
https://github.com/plataformatec/devise/wiki/How-To:-Use-custom-mailer

There should be a layer between the model#send_reset_password_instructions and the the configuration.mailer

**Comment by mcordell** [comment]
You should be able to override the mailer itself, for example, here I create a mailer for [mail gun here](https://github.com/mcordell/grape_token_auth_demo/blob/master/lib/mailgun_mailer.rb). I then use it by configuring it [here](https://github.com/mcordell/grape_token_auth_demo/blob/master/lib/grape_token_auth_setup.rb#L7). 

As for the messages themselves. You can inherit from the email class, e.g.[password reset email](https://github.com/mcordell/grape_token_auth/blob/master/lib/grape_token_auth/mail/messages/password_reset/password_reset_email.rb) and override it at will. Or you could define a class that defines the the public methods found [here](https://github.com/mcordell/grape_token_auth/blob/master/lib/grape_token_auth/mail/message_base.rb#L11-L17) and do whatever you want in the message. 

With your new class you can then configure GTA use it in the configuration as so:

```ruby
GrapeTokenAuth.configuration do |config|
    config.messages = GrapeTokenAuth::Mail::DEFAULT_MESSAGES.merge(reset_password_instructions: YOUR_NEW_CLASS)
end
```

Does that make sense and meet the issue?

**Comment by mcordell** [comment]
@frobichaud see this wiki page: https://github.com/mcordell/grape_token_auth/wiki/Email 

Let me know if you have any suggestions on improving the documentation. Closing this issue for now.
