### ISSUE TITLE
Resource should not generate a new token after signout

### ISSUE THREAD

**Issue by frobichaud** [mcordell/grape_token_auth#19]
The var Configuration::CLIENT_KEY maps to 'client' but in our case it should be 'HTTP_CLIENT'

resource.tokens.delete returns nil:
```
resource.tokens.delete(env[Configuration::CLIENT_KEY])
```
While this succeeds:
```
resource.tokens.delete(env['HTTP_CLIENT])
```

**Comment by frobichaud** [comment]
There's also a bug in the Middleware
```
responses_with_auth_headers
```
Should not be called on /sign_out. It creates new token on the resource.

**Comment by mcordell** [comment]
I'm breaking this issue up into several issues, I think that this [comment](https://github.com/mcordell/grape_token_auth/issues/19#issuecomment-148269477) is a true bug and therefore this issue name was changed to reflect that.
