### ISSUE TITLE
require dep tree is imprevisible

### ISSUE THREAD

**Issue by frobichaud** [mcordell/grape_token_auth#24]
When deploying, we encountered the following issues:
```
`forgiving_load_missing_constant': uninitialized constant GrapeTokenAuth::ResourceCrudBase (NameError)
	from /grape_token_auth/resource/resource_updater.rb:2:in `<module:GrapeTokenAuth>
```
This happens because
```
Dir.glob(File.expand_path('../**/*.rb', __FILE__)).each { |path| require path }
```
might not return an alphabetical ordered list of files.

See
https://github.com/frobichaud/grape_token_auth/commit/2107423bf6d2f10d3684e1aabd8daa4f6e71da0b
and
https://github.com/frobichaud/grape_token_auth/commit/022fb770339c7cba4ac77dc8eda59465d0e104e3

**Comment by mcordell** [comment]
I'm probably going to change it to explicitly load the files,  will fix ASAP.
