### ISSUE TITLE
update documentation (configure_warden)

### ISSUE THREAD

**Issue by stephanvane** [mcordell/grape_token_auth#35]
The documentation instructs to call `GrapeTokenAuth.configure_warden(manager)` in `application.rb`. 

This throws an `undefined method 'configure_warden' for GrapeTokenAuth:Module (NoMethodError)` error. This happens because the configure_warden method is removed in ae43b728c. Could you update the documentation for this?

edit: I added a pull-request, there was an other small typo as well. Documentation seems to be working now. Great project, thanks!

**Comment by mcordell** [comment]
closed in #36
